DROP TABLE IF EXISTS currency CASCADE;
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS district CASCADE;
DROP TABLE IF EXISTS city CASCADE;
DROP TABLE IF EXISTS state_province CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS continent CASCADE;
DROP TABLE IF EXISTS time_zone CASCADE;