DROP TABLE IF EXISTS role_permission CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS user_account CASCADE;
DROP TABLE IF EXISTS security_permission CASCADE;
DROP TABLE IF EXISTS security_role CASCADE;
DROP TABLE IF EXISTS user_status CASCADE;