DROP TABLE IF EXISTS boarding_validation CASCADE;
DROP TABLE IF EXISTS boarding_pass CASCADE;
DROP TABLE IF EXISTS check_in CASCADE;
DROP TABLE IF EXISTS check_in_status CASCADE;
DROP TABLE IF EXISTS boarding_group CASCADE;