DROP TABLE IF EXISTS invoice_line CASCADE;
DROP TABLE IF EXISTS invoice CASCADE;
DROP TABLE IF EXISTS invoice_status CASCADE;
DROP TABLE IF EXISTS exchange_rate CASCADE;
DROP TABLE IF EXISTS tax CASCADE;